[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "vite"
  targetPort = 3000

# Serve correct file types first
[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200
  force = true

# Then fallback to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
